#ifndef CONFIG_HPP
#define CONFIG_HPP

#define PROJECT_NAME "3.3.ShaderClass"
#define PROJECT_VER_MAJOR "0"
#define PROJECT_VER_MINOR "1"
#define PROJECT_VER_PATCH "0"
#define PROJECT_VER  PROJECT_VER_MAJOR << "." << PROJECT_VER_MINOR << "." << PROJECT_VER_PATCH

#endif // CONFIG_HPP
